import type { Product } from "./components/product-card";

export type FullProduct = Product & {
  slug: string;
  subcategory: string;
  material: string;
  color: string;
  size?: string;
  collection: string;
  dek: string;
  designerNote: string;
  designerName: string;
  gallery: string[];
  inRoom: string;
  pairWith: string[];
  details: string[];
  care: string;
  sustainability: string;
  shipping: string;
  rating: number;
  reviewCount: number;
};

export const products: FullProduct[] = [
  {
    slug: "marin-sofa",
    name: "Marin Slipcovered Sofa",
    descriptor: "Belgian linen · Bone",
    price: "$2,890",
    image: "https://images.unsplash.com/photo-1761330439252-325f2091e88d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    hoverImage: "https://images.unsplash.com/photo-1659710197197-354fb99f30aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Marin slipcovered sofa in bone linen",
    tag: { label: "New", tone: "sage" },
    swatches: ["#EDE3D2", "#A89A86", "#5C544A"],
    extraSwatches: 2,
    subcategory: "Sofas",
    material: "Linen",
    color: "Bone",
    size: "84\"",
    collection: "Marin",
    dek: "A low, deep slipcovered sofa in pre-washed Belgian linen on a kiln-dried oak frame. Designed to be sat in — really sat in.",
    designerNote: "We designed the Marin sofa for the way you actually sit — feet up, book open, third cup of coffee. Slipcovered Belgian linen, kiln-dried oak frame, made in North Carolina.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1761330439252-325f2091e88d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1659710197197-354fb99f30aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1571189416642-9d145805cfd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1512880366380-a8446f4321e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1668621183715-f57ed62c4021?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1773061865077-12120d59a217?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["ojai-table", "field-throw", "anza-rug", "olive-vase"],
    details: ["84\" W × 38\" D × 32\" H", "Seat depth 24\", seat height 17\"", "Removable, washable slipcover", "Kiln-dried solid oak frame", "Made in North Carolina"],
    care: "Slipcover is machine washable cold, line dry. Spot clean immediately with cold water and mild soap.",
    sustainability: "Frame from FSC-certified North American white oak. Linen woven in a fourth-generation Flemish mill using OEKO-TEX certified dyes.",
    shipping: "White-glove delivery in 3–5 weeks. Free over $150.",
    rating: 4.8,
    reviewCount: 142,
  },
  {
    slug: "ojai-table",
    name: "Ojai Oak Coffee Table",
    descriptor: "Solid white oak · Natural",
    price: "$1,240",
    image: "https://images.unsplash.com/photo-1581428982868-e410dd047a90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    hoverImage: "https://images.unsplash.com/photo-1647967527216-adea2f078e07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Solid oak coffee table styled with book",
    swatches: ["#C8A98A", "#7B5A40"],
    subcategory: "Coffee Tables",
    material: "Oak",
    color: "Natural",
    size: "48\"",
    collection: "Ojai",
    dek: "A pared-back rectangular coffee table in solid white oak with a soft hand-rubbed oil finish.",
    designerNote: "The Ojai is the table we'd want in our own living rooms — quiet enough to live with, sturdy enough to put your feet on.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1581428982868-e410dd047a90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1647967527216-adea2f078e07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1620812067822-899be8a6a9a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1619911013257-8f1fbc919fc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1773061865077-12120d59a217?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["marin-sofa", "anza-rug", "loma-pendant", "petra-candle"],
    details: ["48\" W × 24\" D × 16\" H", "Solid white oak", "Hand-rubbed natural oil finish", "Mortise and tenon joinery", "Made in North Carolina"],
    care: "Wipe with a soft damp cloth. Re-oil annually with the included care kit.",
    sustainability: "FSC-certified solid wood. Plant-based finish.",
    shipping: "Ships in 2–3 weeks.",
    rating: 4.9,
    reviewCount: 87,
  },
  {
    slug: "june-armchair",
    name: "June Lounge Chair",
    descriptor: "Bouclé · Oat",
    price: "$1,490",
    image: "https://images.unsplash.com/photo-1765828313695-cd872255352f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Two armchairs flank a small table with a lamp",
    tag: { label: "New", tone: "sage" },
    swatches: ["#EDE3D2", "#5C544A", "#7B8470"],
    subcategory: "Chairs",
    material: "Bouclé",
    color: "Oat",
    collection: "June",
    dek: "A low-slung lounge chair with a curved silhouette and a bouclé you'll want to touch.",
    designerNote: "The June started as a sketch on a napkin. The proportions are deliberately a little odd — that's why it feels good.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1765828313695-cd872255352f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1568990416308-c998af4cf9ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1774647001291-7b63c35d5edf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1765828313695-cd872255352f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["marin-sofa", "ojai-table", "loma-pendant", "field-throw"],
    details: ["32\" W × 34\" D × 30\" H", "Bouclé upholstery", "Solid beech frame", "Made in Portugal"],
    care: "Vacuum weekly with upholstery attachment. Spot clean only.",
    sustainability: "OEKO-TEX certified bouclé. FSC beech frame.",
    shipping: "Ships in 3–4 weeks.",
    rating: 4.7,
    reviewCount: 56,
  },
  {
    slug: "hudson-mug",
    name: "Hudson Stoneware Mug",
    descriptor: "Hand-thrown · Cream",
    price: "$32",
    image: "https://images.unsplash.com/photo-1619911013257-8f1fbc919fc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Cream stoneware mug on wooden table",
    tag: { label: "Best Seller", tone: "sage" },
    swatches: ["#F1E9DA", "#2C2620", "#7B8470"],
    subcategory: "Accents",
    material: "Stoneware",
    color: "Cream",
    collection: "Hudson",
    dek: "A satisfyingly heavy hand-thrown stoneware mug, glazed and finished in a small Portuguese studio.",
    designerNote: "We use these every morning. The handle sits right.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1619911013257-8f1fbc919fc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1635847420403-d03e037078a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1586904118338-8ce35f4417dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1635847420403-d03e037078a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["petra-candle", "olive-vase", "ojai-table", "field-throw"],
    details: ["12 oz", "3.75\" H × 3.5\" diameter", "Dishwasher and microwave safe"],
    care: "Dishwasher safe top rack.",
    sustainability: "Lead-free, food-safe reactive glaze. Made in Portugal.",
    shipping: "Ships in 3–5 days.",
    rating: 4.9,
    reviewCount: 412,
  },
  {
    slug: "petra-candle",
    name: "Petra Pillar Candle",
    descriptor: "Soy wax · Tobacco vanilla",
    price: "$58",
    salePrice: "$44",
    image: "https://images.unsplash.com/photo-1603905179139-db12ab535ca9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Black and white pillar candle on wooden holder",
    tag: { label: "Sale", tone: "clay" },
    swatches: ["#F1E9DA", "#1F1B16"],
    subcategory: "Accents",
    material: "Soy wax",
    color: "Bone",
    collection: "Petra",
    dek: "A long-burning soy pillar with notes of tobacco, vanilla, and a faint cedar finish.",
    designerNote: "Lights on a Tuesday, not just a Saturday.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1603905179139-db12ab535ca9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1603897076223-17f346f02a03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1636714560735-9f84a7c06d16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1562050147-fda1cc9a6378?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["hudson-mug", "olive-vase", "ojai-table", "field-throw"],
    details: ["60 hour burn", "3\" diameter × 6\" H", "Soy wax, cotton wick"],
    care: "Trim wick to ¼\" before each burn.",
    sustainability: "100% soy wax. Recyclable glass.",
    shipping: "Ships in 3–5 days.",
    rating: 4.8,
    reviewCount: 238,
  },
  {
    slug: "loma-pendant",
    name: "Loma Pendant",
    descriptor: "Brushed brass · Small",
    price: "$320",
    image: "https://images.unsplash.com/photo-1559924508-1461423083c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    hoverImage: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Brass pendant lamp glowing in a corner",
    swatches: ["#B9905A", "#1F1B16"],
    subcategory: "Accents",
    material: "Brass",
    color: "Brushed brass",
    collection: "Loma",
    dek: "A small, perfectly-weighted pendant in solid brushed brass. Hangs from a fabric-wrapped cord.",
    designerNote: "Hangs low over a kitchen island. Or two of them, side by side.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1559924508-1461423083c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1540932239986-30128078f3c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1581784878214-8d5596b98a01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["ojai-table", "marin-sofa", "olive-vase", "hudson-mug"],
    details: ["8\" diameter × 9\" H", "Solid brushed brass shade", "6 ft fabric-wrapped cord, E26 socket"],
    care: "Dust with a soft dry cloth. Patina will deepen over time.",
    sustainability: "Solid brass, recyclable.",
    shipping: "Ships in 1–2 weeks.",
    rating: 4.7,
    reviewCount: 64,
  },
  {
    slug: "field-throw",
    name: "Field Throw",
    descriptor: "Washed cotton · Oat stripe",
    price: "$148",
    image: "https://images.unsplash.com/photo-1569713198045-f8a69393f3d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Folded white and black striped throw",
    tag: { label: "New", tone: "sage" },
    swatches: ["#EDE3D2", "#5C544A", "#B9755A"],
    subcategory: "Throws",
    material: "Cotton",
    color: "Oat stripe",
    collection: "Field",
    dek: "A generously sized washed cotton throw with a softly faded yarn-dyed stripe.",
    designerNote: "The throw that always ends up on someone's lap.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1569713198045-f8a69393f3d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1619459074324-33d5f591c53e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1705493625048-f3ae8452d249?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1761330439252-325f2091e88d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["marin-sofa", "june-armchair", "petra-candle", "anza-rug"],
    details: ["50\" × 70\"", "100% washed cotton", "Yarn-dyed stripe", "Made in Portugal"],
    care: "Machine wash cold, tumble dry low.",
    sustainability: "OEKO-TEX certified cotton.",
    shipping: "Ships in 3–5 days.",
    rating: 4.9,
    reviewCount: 198,
  },
  {
    slug: "anza-rug",
    name: "Anza Hand-Knotted Rug",
    descriptor: "Wool · 8 × 10",
    price: "$1,890",
    image: "https://images.unsplash.com/photo-1567001605689-687b337ded33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Warm-toned woven rug",
    swatches: ["#C8A98A", "#7B8470"],
    subcategory: "Rugs",
    material: "Wool",
    color: "Camel",
    size: "8 × 10",
    collection: "Anza",
    dek: "A hand-knotted wool rug with a subtle high-low pile in muted, lived-in tones.",
    designerNote: "Anchors a room the way a great pair of boots anchors an outfit.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1567001605689-687b337ded33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1778088442792-29c430a4c93f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1624217350060-f5253f1aad9c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1778088442792-29c430a4c93f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["marin-sofa", "ojai-table", "june-armchair", "field-throw"],
    details: ["8' × 10'", "100% New Zealand wool", "Hand-knotted in India", "0.5\" pile"],
    care: "Professional cleaning recommended. Vacuum without beater bar.",
    sustainability: "GoodWeave certified. Natural undyed wool.",
    shipping: "Ships in 1–2 weeks.",
    rating: 4.8,
    reviewCount: 73,
  },
  {
    slug: "olive-vase",
    name: "Olive Stoneware Vase",
    descriptor: "Hand-thrown · Tall",
    price: "$96",
    image: "https://images.unsplash.com/photo-1620812067822-899be8a6a9a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "White ceramic vase on oak table",
    swatches: ["#F1E9DA", "#7B8470"],
    subcategory: "Accents",
    material: "Stoneware",
    color: "Bone",
    collection: "Olive",
    dek: "A tall, slender hand-thrown stoneware vase. Reads as sculpture, even empty.",
    designerNote: "We use ours for olive branches in the spring, eucalyptus in the fall.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1620812067822-899be8a6a9a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1562050147-fda1cc9a6378?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1759417479667-13c489eb61f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1759417307380-2384b8b8e070?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["hudson-mug", "petra-candle", "ojai-table", "loma-pendant"],
    details: ["14\" H × 5\" diameter", "Sealed interior, watertight"],
    care: "Hand wash with mild soap.",
    sustainability: "Made in Portugal in a solar-powered studio.",
    shipping: "Ships in 3–5 days.",
    rating: 4.9,
    reviewCount: 121,
  },
  {
    slug: "linnea-duvet",
    name: "Linnea Linen Duvet",
    descriptor: "Belgian linen · Bone",
    price: "$320",
    image: "https://images.unsplash.com/photo-1762199904064-56ddc38eda99?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    hoverImage: "https://images.unsplash.com/photo-1762199904138-d163fe89540a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900",
    alt: "Rumpled white linen duvet in morning light",
    swatches: ["#F1E9DA", "#A89A86", "#5C544A", "#7B8470"],
    extraSwatches: 3,
    subcategory: "Bedding",
    material: "Linen",
    color: "Bone",
    size: "Queen",
    collection: "Linnea",
    dek: "Garment-washed Belgian linen that softens with every wash. The duvet you'll want to stay in.",
    designerNote: "Worth getting in early for.",
    designerName: "Anna, Head of Design",
    gallery: [
      "https://images.unsplash.com/photo-1762199904064-56ddc38eda99?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1762199904138-d163fe89540a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
      "https://images.unsplash.com/photo-1762199904164-fff3ac17fc9e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=1400",
    ],
    inRoom: "https://images.unsplash.com/photo-1778731660248-897f9afcd93d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=2000",
    pairWith: ["field-throw", "petra-candle", "loma-pendant", "olive-vase"],
    details: ["Queen 90\" × 92\"", "Garment-washed Belgian linen", "Hidden button closure", "Interior ties"],
    care: "Machine wash cold, tumble dry low. Will soften with every wash.",
    sustainability: "OEKO-TEX certified Belgian linen.",
    shipping: "Ships in 1 week.",
    rating: 4.9,
    reviewCount: 287,
  },
];

export const productBySlug = (slug: string) => products.find((p) => p.slug === slug);
